import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { CartProvider } from '../providers/CartProvider'
import CartInfo from '../components/CartInfo'
import ClearCartButton from '../components/ClearCartButton'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <CartProvider>
      <div className={styles.container}>
        <Head>
          <title>Cart</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Cart
          </h1>

          <CartInfo /> 

          <div className={styles.grid}>
            <Link href="/checkout">
              <a className={styles.card}>Checkout</a>
            </Link>
          </div>
        </main>
      </div>
    </CartProvider>
  )
}
