import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import CartFooter from '../components/CartFooter'
import ProductGrid from '../components/ProductGrid'
import { CartProvider } from '../providers/CartProvider'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <CartProvider>
    <div className={styles.container}>
      <Head>
        <title>Bible Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bible Store
        </h1>

        <p className={styles.description}>
          <i>It is written, ‘My house shall be a house of prayer,’ <br/> but you have made it a den of robbers.</i>
        </p>

        <ProductGrid />
      </main>


      <CartFooter />
    </div>
    </CartProvider>
  )
}
