import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

function Summary(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Checkout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Order summary
        </h1>

        <p className={styles.description}>
          Order number: {props.orderId}
        </p>
        <p className={styles.description}>
          Order total: $0.50
        </p>
      </main>
    </div>
  )
}

// This gets called on every request
export async function getServerSideProps({ query }) {

  return {
    props: {
      orderId: query.orderId
    }
  };
}

export default Summary;