import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { retrieveOrder } from '../utils/DBUtils'
import { formatCurrency } from '../utils/Utils'

function Summary(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Checkout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Order summary
        </h1>

        <p className={styles.description}>
          <b>Order #:</b> {props.orderId} <br/>
          <b>Order total:</b> {props.orderTotal}
        </p>
      </main>
    </div>
  )
}

// This gets called on every request
export async function getServerSideProps({ query }) {
  const orderInfo = await retrieveOrder(query.orderId);
  return {
    props: {
      orderId: query.orderId,
      orderTotal: formatCurrency(orderInfo.total),
    }
  };
}

export default Summary;